# Generated by Django 3.2.5 on 2021-07-21 10:58

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210720_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
